name: fan_carousel_image_slider
description: A fantasy carousel slider widget. only for displaying online and local images.
version: 0.1.2
homepage: https://github.com/marjandn/fan_carousel_image_slider

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

 
flutter:
